### ISSUE TITLE
create a data package for the text

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#1]
This issue will be closed when the appropriate parts and pieces are set up so that the Tyler text is available as a data package.

This includes descriptive DESCRIPTION, `README.qmd`, data wrangling (in `data-raw`), data documentation (in Roxygen format).

**Comment by nicholasjhorton** [comment]
We want to hold off for now, but it might be helpful to start to stub things out once decisions have been finalized for #5

**Comment by Casey308** [comment]
I think this is definitely something to discuss on Tuesday.

**Comment by nicholasjhorton** [comment]
I'm imagining that the package could be used in courses like STAT231 (and replace or augment the `DickinsonPoems` package).

**Comment by nicholasjhorton** [comment]
See https://github.com/STAT325-S24/HistoryAmherstCollege/commit/7405b55eba5a9ae7360d6b969d7047c38b007851 for the first steps on this front.

IMPORTANT NOTE: I had to add in the `HistoryAmherstCollege.Rproj` file into GitHub control. It's likely this will generate a merge conflict since you all will have had equivalently named files. 

I would **strongly** encourage you to try to pull/fetch before you do any further work (you may need to delete your copy of your file to be able to pull/fetch.

Questions? Issues? Please don't hesitate to reach out with a new issue or via DM.

**Comment by nicholasjhorton** [comment]
First cut at real data, see https://github.com/STAT325-S24/HistoryAmherstCollege/commit/31bc62ed596964cf39026d285d75e0510a4f9a26

I'm closing this in favor of separate smaller issues for the package that I believe that we can crowdsource.
