### ISSUE TITLE
Get images

### ISSUE THREAD

**Issue by Casey308** [STAT325-S24/HistoryAmherstCollege#10]
There are many images in the text that right now are inaccessible, since we just scanned the text.  Is there something we can do about this?

This issue will be closed when the images are added to the repo and described in some fashion.

**Comment by nicholasjhorton** [comment]
I believe that it should be straightforward to create screenshots of the images from the scanned pdf. This is not a top priority task but one that can be done in parallel to others.

**Comment by nicholasjhorton** [comment]
This can easily be done in parallel. But some questions: where to store the images? What file format? Naming format?

**Comment by nicholasjhorton** [comment]
What about putting these into `inst/extdata`? This would facilitate their use in a data package (see #1).

**Comment by nicholasjhorton** [comment]
Questions: 

1. what file format? (jpg? png?)
2. what naming scheme (`page_0XX.png`?)
3. how to deal with the Figure captions.

**Comment by Casey308** [comment]
This is hopefully done with https://github.com/STAT325-S24/HistoryAmherstCollege/commits/main/.  I named the images based on the page in the PDF, so that reviewing them might be easier (plus they don't have page numbers in the book).  How does this look?

**Comment by nicholasjhorton** [comment]
@Casey308 this looks great. Here's the commit that I reviewed: https://github.com/STAT325-S24/HistoryAmherstCollege/commit/56cec01d9ebcceabe9e5211613d6e332a6fd3d82

**Comment by Casey308** [comment]
Made a slight fix to one file name with: https://github.com/STAT325-S24/HistoryAmherstCollege/commit/03f47ebb537ed22103af2b39f83d5ff3a0865c82.  Closing the issue now.
