### ISSUE TITLE
Explore sub page titles 

### ISSUE THREAD

**Issue by Casey308** [STAT325-S24/HistoryAmherstCollege#11]
The sub page titles are sometimes interesting, on every odd numbered page.  Is this something we want to work on grabbing?

**Comment by Casey308** [comment]
Some examples of these are: 
  "HATED MONEY. 31"
  "CASH FUNDS. 613"
  "THE SHEPARD CABINET. 623"

Using some sort of routine to get these based on the capital letters and numbers following it could be interesting.

**Comment by nicholasjhorton** [comment]
See also #5 for related discussion.

**Comment by nicholasjhorton** [comment]
I would propose to hold off on working on this issue for the time being.

**Comment by nicholasjhorton** [comment]
Closed in favor of #23
