### ISSUE TITLE
split text into separate chapters

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#12]
The https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/data-raw/amherst_history.txt is cumbersome to work with since it's monolithic. 

I propose to create separate chapters that can be worked on in parallel (e.g., to address footnotes #7).

This issue will be closed when a script is added to `data-raw` with the output as well as the individual chapter files.

**Comment by nicholasjhorton** [comment]
Done via https://github.com/STAT325-S24/HistoryAmherstCollege/issues/12

@Casey308 can you please review and let me know if you see any issues? If no issues, can you please close this issue?

**Comment by Casey308** [comment]
This was done by Nick with https://github.com/STAT325-S24/HistoryAmherstCollege/commit/f3a9f0240d9fb9238c468bb6c43dc4cab87aee1b.

**Comment by Casey308** [comment]
Sorry for the delayed feedback.  I wonder if we should split the appendix into its own chapter?  Besides that it all looks good.

**Comment by nicholasjhorton** [comment]
That's a great suggestion. 

Might you be willing to implement it?

**Comment by Casey308** [comment]
Done with https://github.com/STAT325-S24/HistoryAmherstCollege/commit/62d28aadad5bc5efe6947394c7c65e5920764283.  Closing this now.

**Comment by nicholasjhorton** [comment]
Thanks for your work on this front: the commit looks great.
