### ISSUE TITLE
create a website for the book

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#14]
This issue will be closed when a stub website is set up for this project using `ghpages`.

At a minimum, it would include:

- an about tab
- information about the book
- information about the data package

**Comment by nicholasjhorton** [comment]
@Casey308 might you be willing to take this on for the current sprint?

**Comment by Casey308** [comment]
If we wanted to use a premade theme, I think you would have to do it as the owner of the repo (see https://pages.github.com/).  If we want to build it from the ground up I think I should be able to do this, although it may not be pretty.  

Any thoughts?

**Comment by nicholasjhorton** [comment]
Any thoughts on a suggested theme?

**Comment by nicholasjhorton** [comment]
See https://quarto.org/docs/publishing/github-pages.html for some additional documentation.

**Comment by nicholasjhorton** [comment]
Is it possible to stub out something simple to ensure that the issues with workflows (#31) isn't causing problems?

**Comment by Casey308** [comment]
Can you check this out: https://stat325-s24.github.io/HistoryAmherstCollege/.  @nicholasjhorton

**Comment by nicholasjhorton** [comment]
This looks great. I'm closing this in favor of separate issues for next steps with the website.
