### ISSUE TITLE
fix footnotes for chapters 03-06

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#15]
This issue will be closed when someone has updated the footnotes in these chapters and someone else has reviewed the pull request.

- [ ] chapter 3 reviewed
- [ ] chapter 4 reviewed
- [ ] chapter 5 reviewed
- [ ] chapter 6 reviewed

**Comment by nicholasjhorton** [comment]
@nicholasjhorton will review Adam's work.

**Comment by arogers24** [comment]
https://github.com/STAT325-S24/HistoryAmherstCollege/commit/01ff335da89f95f84321cc38f7894042639775d9 
There is a footnote on page 63 that I cannot find. Also, there is a random "5" at the bottom of page 65. It's also in the pdf, so I left it. There was also a missing page heading for page 72 that I added in

**Comment by Casey308** [comment]
I saw a lot of random numbers at the bottom of pages in my chapters too, and they seemed to be counting up (18, 19 ...).  Does anyone know what these are?

**Comment by Casey308** [comment]
@nicholasjhorton, have you reviewed this work?  If it looks good could you please close this issue?

**Comment by nicholasjhorton** [comment]
This looks great, modulo two minor comments. @arogers24 can you please the two remaining issues I tagged in your commit then close this issue?

**Comment by nicholasjhorton** [comment]
Any updates on this front? Thanks in advance for any guidance @arogers24

**Comment by arogers24** [comment]
@nicholasjhorton I only saw one comment for the typo "presideint." I committed and pushed the change (https://github.com/STAT325-S24/HistoryAmherstCollege/commit/3faef5eaa84c8d14111535d9cb92709696b78b63). You said there was another one, but I couldn't find it.

**Comment by nicholasjhorton** [comment]
Thanks!

I concur that I could only see one comment. I'm closing the issue.
