### ISSUE TITLE
check for missing page numbers

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#23]
@nicholasjhorton may have inadvertently lost some of the page numbers in his pre-editing of https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/data-raw/amherst_history.txt.

He will investigate.

**Comment by nicholasjhorton** [comment]
@nicholasjhorton spoke with @tknightly24 and @jpapagelis24 about their creation of a table of these lines that follow three blanks (see #3). Their supplementary table (a side of their work to process the page breaks) will be helpful for this issue as well as #11.

**Comment by nicholasjhorton** [comment]
@nicholasjhorton will be able to take this once the table of page subtitles and numbers is available

**Comment by nicholasjhorton** [comment]
See https://github.com/STAT325-S24/HistoryAmherstCollege/commit/1f6e5f4b2919a71e7b296cf9044cc63cb6ff6441 and https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/data-raw/04_processing_subtitles.pdf for a collated list.

I will try to fix the first few chapters to see what's involved.

**Comment by nicholasjhorton** [comment]
Here's the fixes for chapters 1 and 2: more work is needed for the other chapters.

https://github.com/STAT325-S24/HistoryAmherstCollege/commit/641ea8f5cb47b7eb6df014bf104e0af742743bc0

Once reviewed, we will need to rerun the whole workflow.

**Comment by nicholasjhorton** [comment]
My proposal is that we devote a chunk of time in class today to crowdsourcing the remaining chapters.

**Comment by jpapagelis24** [comment]
@nicholasjhorton I checked over chapters 24, 26, 27. I was thinking we could make a checklist of that chapters that we've looked over. I'm fine with continuing from the end if you want to start from the beginning!

**Comment by jpapagelis24** [comment]
- [x] 0
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13
- [x] 14
- [x] 15
- [x] 16
- [x] 17
- [x] 18
- [x] 19
- [x] 20
- [x] 21
- [x] 22
- [x] 23
- [x] 24
- [x] 25
- [x] 26
- [x] 27
- [x] 28
- [ ] 29

**Comment by Casey308** [comment]
Below are links to commits for 15 and 16, 17,18,19 and 20


https://github.com/STAT325-S24/HistoryAmherstCollege/commit/4bb2c897f2300ab91123b60b8fedeb308b8934c7

https://github.com/STAT325-S24/HistoryAmherstCollege/commit/0d96c9212e1feb93adf8e6e56a5eadd3c41fe5d0

https://github.com/STAT325-S24/HistoryAmherstCollege/commit/318ccd3e34b014c3b63499a9e01b4994bf2ba27f

22,23,24 : https://github.com/STAT325-S24/HistoryAmherstCollege/commit/ab00ac98df785e0dcd4c4f10501be93fae177d8c

More: https://github.com/STAT325-S24/HistoryAmherstCollege/commit/6af03147ee813c1bd812ba391fcca62c986f3e7d

13: https://github.com/STAT325-S24/HistoryAmherstCollege/commit/c685b7e9431162d71b4e41ed95c339e66df9dc9f

**Comment by Casey308** [comment]
I also checked a lot of chapters and they had no issues

**Comment by nicholasjhorton** [comment]
Many thanks!

Unfortunately, I'm still unable to render https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/data-raw/02_dehyphenate.qmd. And the error message doesn't give any indication of which chapter or which line is problematic.

If it's possible for someone to investigate that would be most helpful.

**Comment by jpapagelis24** [comment]
Checked all of the chapters except for 29 which is the appendix.

Edits on chapter 14: 325d83332cf4b8e9f0699547745747d2b224b40b

Edits on Chapter 28: 50cda002c73476fd12f73a61dde3612097143291

**Comment by nicholasjhorton** [comment]
This looks really great!

Here's what I see as missing page numbers as of today:

- 294 (chapter 16, see #52)
- 379 (chapter 19)
- 649 (first page of appendix)
- 651
- 654
- 658
- 660

**Comment by jpapagelis24** [comment]
@nicholasjhorton I took care of all of those page numbers!
 See commit: 168e789b02cba3c8053d6e20b27afde71027f932
