### ISSUE TITLE
create example of how "testthat" tests can be used

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#25]
See https://testthat.r-lib.org

This is needed for #2

**Comment by nicholasjhorton** [comment]
@arogers24 I see that https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/data-raw/case-01-check.txt has been added to the repo. Are there other files associated with this issue? Any updates?

**Comment by arogers24** [comment]
@nicholasjhorton Yes there is another file called `case-01-test.txt`. The idea behind this was to have some Lorem Ipsum text with hyphens on the end of each line. The following line then starts with a word and then different cases for different forms of punctuation. This is our `test` file. Then there is a `check` file that has the expected output after we run our function. I'm still playing around with `test_that()` to get this to work.

**Comment by nicholasjhorton** [comment]
I suspect that the time to explore regression testing for the hypenation routines has passed. So I'm closing this issue.
