### ISSUE TITLE
Typos within original text.

### ISSUE THREAD

**Issue by FranciscoJFM02** [STAT325-S24/HistoryAmherstCollege#26]
How should we approach typos in the original text? Should we go in and fix these or leave them? I did not find many of these, but I have linked an example from page 221, Chapter 13 (There is a missing period at the end of the quote).
![Screenshot (40)](https://github.com/STAT325-S24/HistoryAmherstCollege/assets/144079668/8fa2941d-1cfa-437d-8790-4df639cb9ea0)

**Comment by Casey308** [comment]
Does anyone have any thoughts on this?  I think perhaps we should just leave them in.

**Comment by nicholasjhorton** [comment]
I would encourage fixes of obvious typos of this sort.

**Comment by FranciscoJFM02** [comment]
Fix issues when they pop-up, but save these minor edits for the end/future work.
