### ISSUE TITLE
Misc numbers at the bottom of pages

### ISSUE THREAD

**Issue by jpapagelis24** [STAT325-S24/HistoryAmherstCollege#27]
There are miscellaneous numbers at the bottom of some of the pages. It seems to be some sort of scanning number. We have decided to remove them.

See https://github.com/STAT325-S24/HistoryAmherstCollege/issues/15

**Comment by nicholasjhorton** [comment]
![Image](https://github.com/STAT325-S24/HistoryAmherstCollege/assets/530542/585a9808-2b4d-48cf-8fba-9923c4a17216)

Here's an example (stray 5) from page 65.

We all agreed (2024-03-28) that these should be removed when they appear.
