### ISSUE TITLE
Appendix not present in cleaned folders

### ISSUE THREAD

**Issue by Casey308** [STAT325-S24/HistoryAmherstCollege#30]
I'm not sure if this is because the routines used only looked at files starting "chapter", but the appendix is not present in the depaginated folder.  Is this something that needs to be dealt with by renaming the appendix file, or something we can just manually fix?

**Comment by nicholasjhorton** [comment]
Methinks that there will need to be additional code to process the appendix (but that it shouldn't be an issue).

An ugly but probably fine workflow might be to rename `appendix` to `chapter29`.

**Comment by nicholasjhorton** [comment]
@jpapagelis24 and @tknightly24 can you please review?

**Comment by nicholasjhorton** [comment]
The plan is for @tknightly24 and @jpapagelis24 to add an additional line into their wrangling file (which will be renamed something like (`data-raw/01_process_pages.qmd`).

**Comment by nicholasjhorton** [comment]
I would propose that we rename `appendix` to `chapter29` and indicate somewhere that chapter 29 is the appendix.

**Comment by nicholasjhorton** [comment]
Fixed via https://github.com/STAT325-S24/HistoryAmherstCollege/commit/79d7266817df10490093417c98f4aed913b05c49
