### ISSUE TITLE
Remove workflows

### ISSUE THREAD

**Issue by Casey308** [STAT325-S24/HistoryAmherstCollege#31]
Is this something you could do @nicholasjhorton?

**Comment by nicholasjhorton** [comment]
I messed something up here (apologies). Can we find a time to explore what would be needed to fix the workflows?

**Comment by nicholasjhorton** [comment]
Let me take another look.

**Comment by nicholasjhorton** [comment]
Alas, I've not found a way to fix this issue. I'm closing it since I believe that it's just an annoyance and not a major complication.
