### ISSUE TITLE
defootnoting in the appendix

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#33]
@tknightly24 when you have a chance can you please review my changes to the appendix?

**Comment by nicholasjhorton** [comment]
@tknightly24 might you be willing to review these changes? Thanks in advance, Nick

https://github.com/STAT325-S24/HistoryAmherstCollege/commit/6c8d2121e5714e99357a882bcfdc00c6cb66f25b

**Comment by tknightly24** [comment]
Taking a look right now

**Comment by tknightly24** [comment]
This looks good. I am curious, though, at the end of the appendix, did the last couple of lines get cut off and had to be added manually? From the revisions that is what it seems like.

**Comment by nicholasjhorton** [comment]
That's exactly right. https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/data-raw/amherst_history_orig.txt has it all but it's a mess.
