### ISSUE TITLE
Check Repagination 

### ISSUE THREAD

**Issue by tknightly24** [STAT325-S24/HistoryAmherstCollege#34]
There are some instances (ex: lines 55-58 in chapter 0) where the page breaks are not removed after running the repagination code. (see #3)

**Comment by nicholasjhorton** [comment]
How goes the progress on this front? I saw a few issues but wanted to wait to report until you two had closed this issue.

**Comment by jpapagelis24** [comment]
@nicholasjhorton I fixed this with commit 79757cfa2a51ad1645c6f7ac9fb11f9842c5679c

**Comment by nicholasjhorton** [comment]
@jpapagelis24 @tknightly24 might you be willing to update this issue with the current status of this work? Thanks in advance, Nick

**Comment by jpapagelis24** [comment]
@nicholasjhorton I'm pretty sure this is all good, so I'm closing this issue!
