### ISSUE TITLE
Remove tables and replace with summary in original files. Was: (Need to modify chapter 28 with repagination due to the spacing of the tables )

### ISSUE THREAD

**Issue by tknightly24** [STAT325-S24/HistoryAmherstCollege#35]
This issue extends #3. In chapter 28, there are tables at the end of the chapter that were scanned incorrectly such that each of the entries in the table is separated by multiple spaces (similar to a page break). This caused the code created for issue #3 to add these entries as page numbers at the end of the chapter 28 table.

**Comment by nicholasjhorton** [comment]
I'm not sure what's meant here: can you please elaborate and/or address? Thanks in advance, Nick

**Comment by tknightly24** [comment]
@nicholasjhorton, I just updated the description of the issue. Is it clearer now?

**Comment by nicholasjhorton** [comment]
Thanks for the updated description: that's most helpful.

What's needed to fix/close this issue? Might you be willing to explore next steps?

**Comment by nicholasjhorton** [comment]
Nice work, thanks!
