### ISSUE TITLE
Make a table of the location of all tables in the text

### ISSUE THREAD

**Issue by Casey308** [STAT325-S24/HistoryAmherstCollege#37]
Instead of images we are doing this.  The tables are all in the following places:
pdf_page (book_page)
15 (IX)
335 (321)
412-413 (392-393)
494 (465)
507 (478)
650 (607)
655 (613)
657-658 (615-616)
668-670 (626-628)
676  (632)  
680  (636) 
688  (644)
693-698   (649-654)
699-700     (655-656)
701-702  (657-658)

**Comment by Casey308** [comment]
Done with https://github.com/STAT325-S24/HistoryAmherstCollege/commit/66dba08e49d9e0713a1f8af92dbca79c76a189c5, but the titles need review and need to make it an actual file.

**Comment by nicholasjhorton** [comment]
See #40

**Comment by Casey308** [comment]
I believe this is done with https://github.com/STAT325-S24/HistoryAmherstCollege/commit/ad4ab3cca38ae63e9fc074104260303b26a1524c.
