### ISSUE TITLE
add additional datasets to the data package

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#40]
I'm imagining

- `history_tables` (chapter/page locations and title of tables)
- `history_chapters` (chapter titles)
- `history_subtitles` (page subtitles)
- `history_figures` (plates and figures)

Like other issues for the data package, this also requires documentation to be added to https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/R/data.R

**Comment by nicholasjhorton** [comment]
@nicholasjhorton has done `history_subtitles` (see 04 in the workflow)

@Casey308 is working on `history_tables` and `history_figures`

@FranciscoJFM02 is working on `history_toc`

**Comment by Casey308** [comment]
I believe that tables and figures are done with https://github.com/STAT325-S24/HistoryAmherstCollege/commit/ad4ab3cca38ae63e9fc074104260303b26a1524c.  @nicholasjhorton, could you review this?

**Comment by FranciscoJFM02** [comment]
This all looks good to me. Can you look over the documentation @nicholasjhorton?

**Comment by nicholasjhorton** [comment]
This looks great: I'm closing the issue.
