### ISSUE TITLE
stub out some analyses (and re-render README)

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#42]
I've added in a more informative README (that mentions the website among other things).

Longer term it would be helpful to rerun this with some additional analyses (once #41 and #39 are complete). For now this is on hold.

**Comment by nicholasjhorton** [comment]
See stubbed file at https://github.com/STAT325-S24/HistoryAmherstCollege/commit/425737f8c144c865a70731995c207d429ee5513c

**Comment by Casey308** [comment]
I think some analyses we could do are LDA modelling and named entity recognition with the text. This should be fairly straightforward.  Does that sound like a good start?

**Comment by nicholasjhorton** [comment]
I think that those are great suggestions.

I suspect the named entity will be quite interesting given the local connection.

**Comment by Casey308** [comment]
Frankie and I added some basic Named Entity analyses to the readme with https://github.com/STAT325-S24/HistoryAmherstCollege/commit/0cacd9ad806048c32d11f5a514557dd736cd0c2c.  How does that look, or were you thinking of something more in depth?

**Comment by nicholasjhorton** [comment]
Done: thanks @FranciscoJFM02 and @Casey308!
