### ISSUE TITLE
document objects in the package

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#47]
At present https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/R/data.R just has a stub for the data objects in the package. Some documentation is needed (then `roxygen2::roxygenize()` needs to be run).

**Comment by Casey308** [comment]
I annotated tables, figures, and subtitles, which may need review.  Anno and text are the only two who currently need documentation currently.

**Comment by nicholasjhorton** [comment]
I can take this on.

**Comment by nicholasjhorton** [comment]
Done via https://github.com/STAT325-S24/HistoryAmherstCollege/commit/c508d784ac9345640a284f5a453ffdf91faa579f
