### ISSUE TITLE
augment website with some background information and guidance

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#50]
@Casey308 stubbed out a website (see https://stat325-s24.github.io/HistoryAmherstCollege)

This issue will be closed when there's some additional background information and guidance for the user.

**Comment by FranciscoJFM02** [comment]
The main page and book_info seem pretty straightforward here. They can be pretty similar to what is contained in the DESCRIPTION files. I think the data info can have a couple of examples of the datasets in the package, along with some visual element that comes from #42.

**Comment by nicholasjhorton** [comment]
That sounds like a good plan. 

Is someone able to take this on?

**Comment by nicholasjhorton** [comment]
Done (for now).
