### ISSUE TITLE
issues with depaginator

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#52]
It looks like there are some issues with the depagination code (or the underlying files in `data-raw`):

```
of being able to carry on his department, at least through the  
first term of the next year.  
 
 
 
294 HISTORY OF AMHERST COLLEGE.

"But the very first week of labor," we quote from his journal,
```

See https://github.com/STAT325-S24/HistoryAmherstCollege/blob/3d6f46b709b1b72d1c6b5ccc814be9f02d0e28c6/data-raw-depaginate/chapter16_cleaned.txt#L550

@jpapagelis24 and @tknightly24 can you please investigate?

**Comment by jpapagelis24** [comment]
This is fixed. There was a space missing!

**Comment by nicholasjhorton** [comment]
Many thanks. 

I was not able to see what was missing.

See https://github.com/STAT325-S24/HistoryAmherstCollege/commit/168e789b02cba3c8053d6e20b27afde71027f932 for your changes.
