### ISSUE TITLE
Minor issue in "page_number" variable name in history_toc.rda

### ISSUE THREAD

**Issue by FranciscoJFM02** [STAT325-S24/HistoryAmherstCollege#53]
@nicholasjhorton Currently the page_number variable has a "[, 1]" attached to its variable name. Could you help me remove this?

**Comment by nicholasjhorton** [comment]
Done via https://github.com/STAT325-S24/HistoryAmherstCollege/commit/85980e0ba1cd0b94dca4f8eccf3f6517eadc766a
