### ISSUE TITLE
ensure that first set of footnotes are correctly formatted

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#7]
This issue will be closed when footnotes are correctly formatted (per the discussion in #6).

**Comment by nicholasjhorton** [comment]
@jpapagelis24 when you have a chance can you please review this commit and confirm that I've correctly reformatted the footnotes from chapters 1 and 2? Thanks in advance, Nick

https://github.com/STAT325-S24/HistoryAmherstCollege/commit/1ffde7937db31461addf186428f44e3a00751905

**Comment by jpapagelis24** [comment]
Looks good for chapters 1 and 2!
